#!/usr/bin/env python3
print("-----Welcome to fibonacci-gen-----")
print("How many lines should be outputted? ")

try:
	maxlines = int(input())
except:
	print("That wasn't a number.")
	quit()

num1 = 0
num2 = 1
activelines = 0
while activelines < maxlines:
	num3 = num1 + num2
	print(str(num3))
	num1 = num2
	num2 = num3
	activelines += 1
